set_property SRC_FILE_INFO {cfile:{C:/Users/rareg/Vivado projects/project_01_led_blinker/project_01_led_blinker.srcs/constrs_1/new/constrints.xdc} rfile:../../../project_01_led_blinker.srcs/constrs_1/new/constrints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports led]
